server:
  port: ${SERVER_PORT:8087}

spring:
  application:
    name: reports-service

app:
  jwt:
    secret: ${JWT_SECRET:VGhpc0lzQVN1cGVyU2VjdXJlSldUU2VjcmV0S2V5Rm9yRGV2TXVzdEJlQXRMZWFzdDMyQ2hhcnM=}
  services:
    congreso-url: ${CONGRESO_SERVICE_URL:http://congreso-service}
    auth-url: ${AUTH_SERVICE_URL:http://auth-service}
    activities-url: ${ACTIVITIES_SERVICE_URL:http://activities-service}
    asistencias-url: ${ASISTENCIAS_SERVICE_URL:http://ms-asistencias}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-service:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /api-docs

logging:
  level:
    root: INFO
    com.example.reports: DEBUG
